"""Agregar campo activo a Afiliado

Revision ID: a83e70198752
Revises: 43efe3d2a593
Create Date: 2025-07-11 18:22:20.985202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83e70198752'
down_revision = '43efe3d2a593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
